### PR TITLE
Publish Views to allow them to be overwritten.

### LINKED ISSUE #15: Publish Views to allow them to be overwritten
This is important for devs that don't use Bootstrap.

### PR DESCRIPTION
**Pull request by mikemand**
Closes #15.

The only caveat I can see with this is it will publish the default layout and master intermediary, but not update the views to reflect their new locations. (At least, I don't think Laravel can do that anyway...) Some kind of warning will need to be put in the documentation about that.

### CODE REVIEW

**Comment by mikebronner** [comment]
Hi @mikemand Thank you so much for this PR! I have been waiting to do much with the views until Spark ships, as I want it to integrate with it at the same time. I have so far intentionally not made views publishable, because they are tricky. I understand that if you don't use Bootstrap 3 that's an issue.

I am definitely considering it, and once Spark rolls out will make an update. Thanks!

**Comment by mikemand** [comment]
Not a problem, @mikebronner. I am also waiting on Spark for a few things.

One thing to consider when you do update is to change the tags for config, public, views (and translations if you use them) from being all in the `genealabs-laravel-governor` tag, to individual ones so devs can publish only the items they need. For example:

```sh
php artisan vendor:publish --provider="GeneaLabs\LaravelGovernor\Providers\LaravelGovernorServiceProvider" --tag="config"
```

would only publish the config and 

```sh
php artisan vendor:publish --provider="GeneaLabs\LaravelGovernor\Providers\LaravelGovernorServiceProvider" --tag="views"
```

would only publish the views, and so on and so forth. I'm not 100% on the syntax because I don't have a project with your package installed open at the moment, but it should be near enough to give you the idea.

**Comment by mikebronner** [comment]
Ah, yes, good catch on the tags. I have been doing that in other packages, must have missed it on this one. Will do! :)

**Comment by mikebronner** [comment]
@mikemand Sorry for the long delay. I have been unable to work on this package lately due to work constraints, but will be doing so over the next week. Your PR hasn't been forgotten, I will look into it.

**Comment by mikemand** [comment]
Hi Mike,

No problem. I understand how that goes. :)

**Comment by mikebronner** [comment]
@mikemand I am going to close this PR, as it does not address the issue in a solvable manner. I will update the way the views work, so once published, will still work correctly. Thanks for submitting this, though, and bringing up the topic for discussion. I hope to have this update live in the next few days.

**Pull request closed without merging**
