### PR TITLE
Update LaravelGovernorServiceProvider.php

### PR DESCRIPTION
**Pull request by fwartner**

### CODE REVIEW

**Comment by mikebronner** [comment]
Hi Florian, can you explain what benefits this provides? :) Thanks!

**Comment by fwartner** [comment]
It´s working with L5.2.. Otherwise the Provider will use ```bindShared()```which isn´t present in L5.2

**Comment by jpmurray** [comment]
@fwartner This is make it work on 5.2, thanks. Although trying to run the migrations I get ```[ReflectionException]
  Class  does not exist```

Could it be related to a 5.2 compatibility problem too?

**Comment by jpmurray** [comment]
I'm getting a ```[ReflectionException]
  Class  does not exist``` on trying to run migrations, could it be related to compatibility with 5.2 ? (Otherwise, @fwartner changes does help with 5.2! :+1: )

**Comment by fwartner** [comment]
Great to see, that it´s working! :)

**Comment by jpmurray** [comment]
Hey, just adding the stacktrace of said error up there,

```
[2016-01-13 11:39:19] local.ERROR: exception 'ReflectionException' with message 'Class  does not exist' in /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('')
#1 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(NULL, Array)
#2 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make(NULL, Array)
#3 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(216): Illuminate\Foundation\Application->make(NULL)
#4 /home/vagrant/Code/boilerplate/vendor/genealabs/laravel-governor/database/migrations/2014_11_01_194858_create_roles_users_table.php(17): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#5 /home/vagrant/Code/boilerplate/vendor/genealabs/laravel-governor/database/migrations/2014_11_01_194858_create_roles_users_table.php(17): Illuminate\Support\Facades\App::make(NULL)
#6 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(132): CreateRolesUsersTable->{closure}(Object(Illuminate\Database\Schema\Blueprint))
#7 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(219): Illuminate\Database\Schema\Builder->create('role_user', Object(Closure))
#8 /home/vagrant/Code/boilerplate/vendor/genealabs/laravel-governor/database/migrations/2014_11_01_194858_create_roles_users_table.php(22): Illuminate\Support\Facades\Facade::__callStatic('create', Array)
#9 /home/vagrant/Code/boilerplate/vendor/genealabs/laravel-governor/database/migrations/2014_11_01_194858_create_roles_users_table.php(22): Illuminate\Support\Facades\Schema::create('role_user', Object(Closure))
#10 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(147): CreateRolesUsersTable->up()
#11 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(117): Illuminate\Database\Migrations\Migrator->runUp('2014_11_01_1948...', 3, false)
#12 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(86): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#13 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(77): Illuminate\Database\Migrations\Migrator->run('/home/vagrant/C...', Array)
#14 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#15 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#16 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#17 /home/vagrant/Code/boilerplate/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/Code/boilerplate/vendor/symfony/console/Application.php(787): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/Code/boilerplate/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/Code/boilerplate/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/Code/boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/Code/boilerplate/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}  
```

**Comment by mikebronner** [comment]
Hi @jpmurray thank you for reporting your issue as well. I will look into both these things early next week as soon as I get back from my trip. :)

**Comment by jpmurray** [comment]
@mikebronner Cool. I'll try to find what goes wrong on my end, if I'm lucky, I might be able to! I'll send a pull request in that case! ;-)

**Comment by mikebronner** [comment]
Looking at the trace, it seems to have to do with $app->make() ... guessing that the class is not registered the same way in the IoC container.

**Comment by jpmurray** [comment]
@mikebronner it's already in.

**Comment by jpmurray** [comment]
Just keeping you up to date, @mikebronner, I started to change the reference of `auth.model` config to `auth.providers.users.model` and the migration now work, Now I'm getting trouble with seeding at this point. It fails at the RoleTableSeeder at `$role->users()->attach($superuser);`and I've yet to find why, although the query it tries to insert is `insert into `role_user` (`role_key`, `user_id`) values (0, 1)` (the value for `role_key` seems wrong to me.)

Anyway, I might not be able to finish everything to make a pull request before you might tackle this yourself, but in any case, what I do is at this fork if you want to check anything (and so I don't spam too much this pull request!) https://github.com/jpmurray/laravel-governor/commits/patch-5.2

**Pull request merged**
