### PR TITLE
[laravel-governor] Fix Typo

### PR DESCRIPTION
**Pull request by busayo**

### CODE REVIEW

**Comment by mikebronner** [comment]
Nice catch :) Thanks -- will be overhauling the README as soon as I have all the unit tests in place.

**Comment by busayo** [comment]
Yeah.. I checked the unit tests and wanted to contribute, but then i checked your git history and discovered that you were still in the process of writing all of them. Nice one :+1:  . I wanted to also do a comprehensive tutorial about it on my site [goodheads.io](http://goodheads.io), that's exactly what brought me to the README

**Comment by mikebronner** [comment]
Awesome, go for it! If you have any questions on how things work for writing you tutorial, just ask away. Would also love to hear your feedback on your experience. Im sure there are bottlenecks in the UX that can be improved on. I also plan to add functionality to support multi-tenancy (once Spark is released -- this whole package may be moot if Spark takes care of all of this. Or I may adapt this package to blend into Spark. We'll see.) :)

**Comment by busayo** [comment]
Aha!..Sounds Awesome!!. Thanks, I'm sure i'll contribute to the UX once i discover the bottlenecks and brace up for all the questions i might throw at you as i dig deep into the package! :smile_cat:

**Pull request merged**
